[package]
name = "raytracer"
version = "0.1.0"
authors = ["Christopher Cowan <chrisjoelcowan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
rand = "0.8.0"
